# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQLY0ip3gjnPT_QaXTCWWPftgb5hLZK8
"""

!pip install datasets   # Load dataset

from datasets import load_dataset

dataset = load_dataset("imdb")

print(dataset)

print(dataset["train"][0])

import pandas as pd

train_df = pd.DataFrame(dataset["train"])
test_df = pd.DataFrame(dataset["test"])

print(train_df.head())

print("Train size:", len(train_df))
print("Test size:", len(test_df))

print("\nTrain label dağılımı:")
print(train_df["label"].value_counts())

train_df = train_df.sample(5000, random_state=42)
test_df = test_df.sample(1000, random_state=42)

print("Yeni train size:", len(train_df))
print("Yeni test size:", len(test_df))

import re

def clean_text(text):
    text = text.lower()                        # küçük harfe çevir
    text = re.sub(r'<.*?>', '', text)          # <br /> gibi HTML tagları sil
    text = re.sub(r'[^a-z0-9\s]', '', text)   # noktalama işaretlerini sil
    text = re.sub(r'\s+', ' ', text).strip()  # fazla boşlukları sil
    return text

train_df['text'] = train_df['text'].apply(clean_text)
test_df['text'] = test_df['text'].apply(clean_text)

print("Temizleme tamamlandı!")
print("\nÖrnek temizlenmiş metin:")
print(train_df['text'].iloc[0][:300])

def clean_text_distilbert(text):
    text = re.sub(r'<.*?>', '', text)          # sadece HTML tagları sil
    text = re.sub(r'\s+', ' ', text).strip()   # fazla boşlukları sil
    return text

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words="english",
    ngram_range=(1, 2)
)

X_train = vectorizer.fit_transform(train_df["text"])
X_test = vectorizer.transform(test_df["text"])

y_train = train_df["label"]
y_test = test_df["label"]

print("Geliştirilmiş TF-IDF tamamlandı")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

import torch

# sparse matrix → normal array → tensor
X_train_tensor = torch.tensor(X_train.toarray(), dtype=torch.float32)
X_test_tensor = torch.tensor(X_test.toarray(), dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

print("Tensor dönüşümü tamam")
print("X_train_tensor:", X_train_tensor.shape)
print("y_train_tensor:", y_train_tensor.shape)

import torch.nn as nn

class SentimentNet(nn.Module):
    def __init__(self, input_size):
        super(SentimentNet, self).__init__()
        self.fc1 = nn.Linear(input_size, 256)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(256, 64)
        self.fc3 = nn.Linear(64, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        return x

input_size = X_train_tensor.shape[1]
model = SentimentNet(input_size)

print(model)

import torch.optim as optim

# Modeli ve optimizer'ı sıfırla
model = SentimentNet(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

# Validation split ekle
X_train_final, X_val, y_train_final, y_val = train_test_split(
    X_train_tensor, y_train_tensor, test_size=0.1, random_state=42
)

train_dataset = TensorDataset(X_train_final, y_train_final)
val_dataset = TensorDataset(X_val, y_val)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

num_epochs = 5
loss_history = []
val_loss_history = []

# Early stopping ayarları
best_val_loss = float('inf')
patience = 2          # kaç epoch arka arkaya kötüleşirse dur
patience_counter = 0
best_model_state = None

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    loss_history.append(avg_loss)

    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            val_loss += loss.item()
    avg_val_loss = val_loss / len(val_loader)
    val_loss_history.append(avg_val_loss)

    print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {avg_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

    # Early stopping kontrolü
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        patience_counter = 0
        best_model_state = model.state_dict().copy()  # en iyi modeli kaydet
        print(f"  ✓ Val loss iyileşti, model kaydedildi.")
    else:
        patience_counter += 1
        print(f"  ✗ Val loss iyileşmedi. ({patience_counter}/{patience})")
        if patience_counter >= patience:
            print(f"\nEarly stopping! En iyi val loss: {best_val_loss:.4f}")
            break

# En iyi model ağırlıklarını geri yükle
model.load_state_dict(best_model_state)
print("En iyi model yüklendi.")

import matplotlib.pyplot as plt

actual_epochs = len(loss_history)  # early stopping kaçta durduysa o kadar

plt.figure(figsize=(8, 5))
plt.plot(range(1, actual_epochs+1), loss_history, marker='o', color='blue', label='Train Loss')
plt.plot(range(1, actual_epochs+1), val_loss_history, marker='o', color='red', label='Validation Loss')
plt.title('TF-IDF Neural Network - Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import accuracy_score, classification_report

model.eval()

with torch.no_grad():
    test_outputs = model(X_test_tensor)
    predictions = (test_outputs >= 0.5).float()

accuracy = accuracy_score(y_test_tensor, predictions)
print("Test Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test_tensor, predictions))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(y_test_tensor, predictions)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Negative", "Positive"])
disp.plot(cmap="Blues")
plt.title("TF-IDF Neural Network - Confusion Matrix")
plt.tight_layout()
plt.show()

!pip install gradio

import gradio as gr

def predict_sentiment(text):
    # Temizle
    cleaned = clean_text(text)

    # TF-IDF'e çevir
    vectorized = vectorizer.transform([cleaned])
    tensor = torch.tensor(vectorized.toarray(), dtype=torch.float32)

    # Tahmin yap
    model.eval()
    with torch.no_grad():
        output = model(tensor)
        probability = output.item()
        prediction = "Positive 😊" if probability >= 0.5 else "Negative 😞"
        confidence = probability if probability >= 0.5 else 1 - probability

    return f"{prediction} (Confidence: {confidence:.1%})"

# Gradio arayüzü
app = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(
        lines=4,
        placeholder="Write a movie review here...",
        label="Movie Review"
    ),
    outputs=gr.Textbox(label="Sentiment"),
    title="🎬 Sentiment Analysis App",
    description="Enter a movie review and the model will predict if it's Positive or Negative."
)

app.launch()

!pip install transformers

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.optim as optim

# Tokenizer ve model yükle
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

print("Tokenizer yüklendi!")

# Eğitim ve test metinlerini tokenize et
def tokenize_data(texts, labels, max_length=256):
    encodings = tokenizer(
        list(texts),
        truncation=True,
        padding=True,
        max_length=max_length,
        return_tensors="pt"
    )
    return encodings, torch.tensor(list(labels), dtype=torch.long)

# DistilBERT için orijinal dataset'ten temiz metin al (HTML tag'ları sil, lowercase yapma)
train_df_raw = pd.DataFrame(dataset["train"]).sample(5000, random_state=42)
test_df_raw  = pd.DataFrame(dataset["test"]).sample(1000, random_state=42)

train_df_raw['text_distilbert'] = train_df_raw['text'].apply(clean_text_distilbert)
test_df_raw['text_distilbert']  = test_df_raw['text'].apply(clean_text_distilbert)

train_encodings, train_labels = tokenize_data(train_df_raw["text_distilbert"], train_df_raw["label"])
test_encodings, test_labels   = tokenize_data(test_df_raw["text_distilbert"],  test_df_raw["label"])

print("Tokenization tamamlandı!")
print("Train shape:", train_encodings["input_ids"].shape)
print("Test shape:", test_encodings["input_ids"].shape)

from torch.utils.data import DataLoader, TensorDataset

# Dataset oluştur
train_dataset = TensorDataset(
    train_encodings["input_ids"],
    train_encodings["attention_mask"],
    train_labels
)

test_dataset = TensorDataset(
    test_encodings["input_ids"],
    test_encodings["attention_mask"],
    test_labels
)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

print("DataLoader hazır!")
print("Train batch sayısı:", len(train_loader))

from transformers import AutoModelForSequenceClassification

# DistilBERT modelini yükle
distilbert_model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

# GPU'ya taşı
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
distilbert_model = distilbert_model.to(device)

print("Model yüklendi!")
print("Kullanılan cihaz:", device)

from torch.optim import AdamW
from torch.utils.data import random_split

optimizer = AdamW(distilbert_model.parameters(), lr=2e-5)

# Validation split - train'in %10'u
val_size = int(0.1 * len(train_dataset))
train_size = len(train_dataset) - val_size
train_sub, val_sub = random_split(train_dataset, [train_size, val_size])

train_loader_bert = DataLoader(train_sub, batch_size=16, shuffle=True)
val_loader_bert = DataLoader(val_sub, batch_size=16)

num_epochs = 3
distilbert_loss_history = []
distilbert_val_loss_history = []

# Early stopping ayarları
best_val_loss_bert = float('inf')
patience_bert = 1          # transformer'lar için 1 yeterli
patience_counter_bert = 0
best_model_state_bert = None

for epoch in range(num_epochs):
    # --- Training ---
    distilbert_model.train()
    total_loss = 0
    for batch in train_loader_bert:
        input_ids, attention_mask, labels = [b.to(device) for b in batch]
        optimizer.zero_grad()
        outputs = distilbert_model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader_bert)
    distilbert_loss_history.append(avg_loss)

    # --- Validation ---
    distilbert_model.eval()
    val_loss = 0
    with torch.no_grad():
        for batch in val_loader_bert:
            input_ids, attention_mask, labels = [b.to(device) for b in batch]
            outputs = distilbert_model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            val_loss += outputs.loss.item()
    avg_val_loss = val_loss / len(val_loader_bert)
    distilbert_val_loss_history.append(avg_val_loss)

    print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {avg_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

    # Early stopping kontrolü
    if avg_val_loss < best_val_loss_bert:
        best_val_loss_bert = avg_val_loss
        patience_counter_bert = 0
        distilbert_model.save_pretrained('distilbert_best')
        tokenizer.save_pretrained('distilbert_best')
        print(f"  ✓ Val loss iyileşti, model kaydedildi.")
    else:
        patience_counter_bert += 1
        print(f"  ✗ Val loss iyileşmedi. ({patience_counter_bert}/{patience_bert})")
        if patience_counter_bert >= patience_bert:
            print(f"\nEarly stopping! En iyi val loss: {best_val_loss_bert:.4f}")
            break

# En iyi modeli geri yükle
from transformers import AutoModelForSequenceClassification
distilbert_model = AutoModelForSequenceClassification.from_pretrained('distilbert_best').to(device)
print("En iyi DistilBERT modeli yüklendi.")

import matplotlib.pyplot as plt

actual_epochs_bert = len(distilbert_loss_history)  # early stopping kaçta durduysa o kadar

plt.figure(figsize=(8, 5))
plt.plot(range(1, actual_epochs_bert+1), distilbert_loss_history, marker='o', color='orange', label='Train Loss')
plt.plot(range(1, actual_epochs_bert+1), distilbert_val_loss_history, marker='o', color='red', label='Validation Loss')
plt.title('DistilBERT - Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import accuracy_score, classification_report

distilbert_model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for batch in test_loader:
        input_ids, attention_mask, labels = [b.to(device) for b in batch]
        outputs = distilbert_model(input_ids=input_ids, attention_mask=attention_mask)
        preds = torch.argmax(outputs.logits, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

accuracy = accuracy_score(all_labels, all_preds)
print("DistilBERT Test Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(all_labels, all_preds))

import pickle

# TF-IDF modelini kaydet
torch.save(model.state_dict(), 'tfidf_model.pth')
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

# DistilBERT modelini kaydet
distilbert_model.save_pretrained('distilbert_sentiment')
tokenizer.save_pretrained('distilbert_sentiment')

print("Modeller kaydedildi!")

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(all_labels, all_preds)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Negative", "Positive"])
disp.plot(cmap="Oranges")
plt.title("DistilBERT - Confusion Matrix")
plt.tight_layout()
plt.show()

# ROC-AUC Curve - TF-IDF Neural Network
from sklearn.metrics import roc_curve, auc

model.eval()
with torch.no_grad():
    tfidf_probs = model(X_test_tensor).squeeze().numpy()

fpr_tfidf, tpr_tfidf, _ = roc_curve(y_test_tensor.numpy(), tfidf_probs)
roc_auc_tfidf = auc(fpr_tfidf, tpr_tfidf)

plt.figure(figsize=(7, 5))
plt.plot(fpr_tfidf, tpr_tfidf, color='blue', lw=2, label=f'TF-IDF NN (AUC = {roc_auc_tfidf:.3f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Random Classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - TF-IDF Neural Network')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

print(f"TF-IDF Neural Network ROC-AUC: {roc_auc_tfidf:.4f}")

# ROC-AUC Curve - DistilBERT
import numpy as np
from sklearn.metrics import roc_curve, auc

distilbert_model.eval()
all_probs = []
all_true_labels = []

with torch.no_grad():
    for batch in test_loader:
        input_ids, attention_mask, labels = [b.to(device) for b in batch]
        outputs = distilbert_model(input_ids=input_ids, attention_mask=attention_mask)
        probs = torch.softmax(outputs.logits, dim=1)[:, 1]  # Positive sınıfı olasılığı
        all_probs.extend(probs.cpu().numpy())
        all_true_labels.extend(labels.cpu().numpy())

fpr_bert, tpr_bert, _ = roc_curve(all_true_labels, all_probs)
roc_auc_bert = auc(fpr_bert, tpr_bert)

plt.figure(figsize=(7, 5))
plt.plot(fpr_bert, tpr_bert, color='orange', lw=2, label=f'DistilBERT (AUC = {roc_auc_bert:.3f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Random Classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - DistilBERT')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

print(f"DistilBERT ROC-AUC: {roc_auc_bert:.4f}")

# İki Modelin ROC Curve Karşılaştırması
plt.figure(figsize=(8, 6))
plt.plot(fpr_tfidf, tpr_tfidf, color='blue', lw=2, label=f'TF-IDF NN (AUC = {roc_auc_tfidf:.3f})')
plt.plot(fpr_bert, tpr_bert, color='orange', lw=2, label=f'DistilBERT (AUC = {roc_auc_bert:.3f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Random Classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison - TF-IDF NN vs DistilBERT')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

print(f"\nModel Karşılaştırması:")
print(f"TF-IDF Neural Network AUC: {roc_auc_tfidf:.4f}")
print(f"DistilBERT             AUC: {roc_auc_bert:.4f}")
print(f"DistilBERT farkı:     +{roc_auc_bert - roc_auc_tfidf:.4f}")

import gradio as gr

def predict_distilbert(text):
    cleaned = clean_text_distilbert(text)
    inputs = tokenizer(
        cleaned,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    distilbert_model.eval()
    with torch.no_grad():
        outputs = distilbert_model(**inputs)
        probs = torch.softmax(outputs.logits, dim=1)
        pred = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred].item()

    label = "Positive 😊" if pred == 1 else "Negative 😞"
    return f"{label} (Confidence: {confidence:.1%})"

app2 = gr.Interface(
    fn=predict_distilbert,
    inputs=gr.Textbox(
        lines=4,
        placeholder="Write a movie review here...",
        label="Movie Review"
    ),
    outputs=gr.Textbox(label="Sentiment"),
    title="🎬 Sentiment Analysis - DistilBERT",
    description="Advanced transformer-based sentiment analysis. Enter a movie review to classify it."
)

app2.launch()