# -*- coding: utf-8 -*-
"""sentiment_analysis_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xV8B3HwqTJ24seHLTiciXPO3FvorZpL8
"""

!pip install datasets   # Load dataset

from datasets import load_dataset

dataset = load_dataset("imdb")

print(dataset)

print(dataset["train"][0])

import pandas as pd

train_df = pd.DataFrame(dataset["train"])
test_df = pd.DataFrame(dataset["test"])

print(train_df.head())

print("Train size:", len(train_df))
print("Test size:", len(test_df))

print("\nTrain label dağılımı:")
print(train_df["label"].value_counts())

train_df = train_df.sample(5000, random_state=42)
test_df = test_df.sample(1000, random_state=42)

print("Yeni train size:", len(train_df))
print("Yeni test size:", len(test_df))

import re

def clean_text(text):
    text = text.lower()                        # küçük harfe çevir
    text = re.sub(r'<.*?>', '', text)          # <br /> gibi HTML tagları sil
    text = re.sub(r'[^a-z0-9\s]', '', text)   # noktalama işaretlerini sil
    text = re.sub(r'\s+', ' ', text).strip()  # fazla boşlukları sil
    return text

train_df['text'] = train_df['text'].apply(clean_text)
test_df['text'] = test_df['text'].apply(clean_text)

print("Temizleme tamamlandı!")
print("\nÖrnek temizlenmiş metin:")
print(train_df['text'].iloc[0][:300])

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words="english",
    ngram_range=(1, 2)
)

X_train = vectorizer.fit_transform(train_df["text"])
X_test = vectorizer.transform(test_df["text"])

y_train = train_df["label"]
y_test = test_df["label"]

print("Geliştirilmiş TF-IDF tamamlandı")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

import torch

# sparse matrix → normal array → tensor
X_train_tensor = torch.tensor(X_train.toarray(), dtype=torch.float32)
X_test_tensor = torch.tensor(X_test.toarray(), dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

print("Tensor dönüşümü tamam")
print("X_train_tensor:", X_train_tensor.shape)
print("y_train_tensor:", y_train_tensor.shape)

import torch.nn as nn

class SentimentNet(nn.Module):
    def __init__(self, input_size):
        super(SentimentNet, self).__init__()
        self.fc1 = nn.Linear(input_size, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, 64)
        self.fc3 = nn.Linear(64, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        return x

input_size = X_train_tensor.shape[1]
model = SentimentNet(input_size)

print(model)

import torch.optim as optim

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

print("Hazır")

from torch.utils.data import DataLoader, TensorDataset

# Dataset ve DataLoader oluştur
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

num_epochs = 20

for epoch in range(num_epochs):
    model.train()
    total_loss = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")

from sklearn.metrics import accuracy_score, classification_report

model.eval()

with torch.no_grad():
    test_outputs = model(X_test_tensor)
    predictions = (test_outputs >= 0.5).float()

accuracy = accuracy_score(y_test_tensor, predictions)
print("Test Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test_tensor, predictions))

!pip install gradio

import gradio as gr

def predict_sentiment(text):
    # Temizle
    cleaned = clean_text(text)

    # TF-IDF'e çevir
    vectorized = vectorizer.transform([cleaned])
    tensor = torch.tensor(vectorized.toarray(), dtype=torch.float32)

    # Tahmin yap
    model.eval()
    with torch.no_grad():
        output = model(tensor)
        probability = output.item()
        prediction = "Positive 😊" if probability >= 0.5 else "Negative 😞"
        confidence = probability if probability >= 0.5 else 1 - probability

    return f"{prediction} (Confidence: {confidence:.1%})"

# Gradio arayüzü
app = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(
        lines=4,
        placeholder="Write a movie review here...",
        label="Movie Review"
    ),
    outputs=gr.Textbox(label="Sentiment"),
    title="🎬 Sentiment Analysis App",
    description="Enter a movie review and the model will predict if it's Positive or Negative."
)

app.launch()